services:
  - type: web
    name: nextjs-amazona-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.x
      - key: MONGODB_URI
        value: mongodb+srv://dbuser:Harish2807@cluster0.wgghmay.mongodb.net/nextjs-amazona?retryWrites=true&w=majority&appName=Cluster0
      - key: AUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        value: https://nextjs-a-free.web.app
      - key: NEXT_PUBLIC_SERVER_URL
        value: https://nextjs-a-free.web.app
      - key: NEXT_PUBLIC_APP_NAME
        value: Amazona
      - key: NEXT_PUBLIC_APP_DESCRIPTION
        value: An Amazon clone built with Next.js, MongoDB, Shadcn
      - key: NODE_ENV
        value: production
